open Parser

let tokenToString : token -> string = function
  | AND_IF      -> "&&"
  | OR_IF       -> "||"
  | DSEMI       -> ";;"
  | DLESS       -> "<<"
  | DGREAT      -> ">>"
  | LESSAND     -> "<&"
  | GREATAND    -> ">&"
  | LESSGREAT   -> "<>"
  | DLESSDASH   -> "<<-"
  | CLOBBER     -> ">|"
  | LESS        -> "<"
  | GREAT       -> ">"
  | PIPE        -> "|"
  | AMP         -> "&"
  | SEMI        -> ";"
  | IF          -> "if"
  | THEN        -> "then"
  | ELSE        -> "else"
  | ELIF        -> "elif"
  | FI          -> "fi"
  | DO          -> "do"
  | DONE        -> "done"
  | CASE        -> "case"
  | ESAC        -> "esac"
  | WHILE       -> "while"
  | UNTIL       -> "until"
  | FOR         -> "for"
  | IN          -> "in"
  | LBRACE      -> "{"
  | RBRACE      -> "}"
  | BANG        -> "!"
  | LPAREN      -> "("
  | RPAREN      -> ")"
  | IO_NUMBER n -> string_of_int n
  | NAME n      -> n
  | WORD n      -> n
  | EOF         -> "EOF"
  | NEWLINE     -> "NL"
